name: opusfile_dart
description: A Dart package wrapping the Opus decoder.
version: 0.0.1
repository: https://github.com/nmfisher/opusfile_dart

environment:
  sdk: ^3.3.0

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  ffigen:
  native_assets_cli: ^0.5.0
  native_toolchain_c: ^0.4.0
  
ffigen:
  output: 'lib/src/opusfile_dart.g.dart'
  headers:
    entry-points:
      - 'native/include/OpusFileDartCApi.h'
    include-directives:
      - 'native/include/OpusFileDartCApi.h'
  ffi-native:
    assetId: package:opusfile_dart/opusfile_dart.dart
