name: opusfile_dart
description: A Dart package wrapping the Opus decoder.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-76.0.dev

dependencies:
  ffi:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  ffigen:
  native_assets_cli: ^0.5.0
  native_toolchain_c: ^0.4.0
  
ffigen:
  output: 'lib/src/opusfile_dart.g.dart'
  headers:
    entry-points:
      - 'native/include/OpusFileDartCApi.h'
    include-directives:
      - 'native/include/OpusFileDartCApi.h'
  ffi-native:
    assetId: package:opusfile_dart/opusfile_dart.dart