// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

@ffi.Native<
        ffi.Pointer<ffi.UnsignedChar> Function(
            ffi.Pointer<ffi.Void>, ffi.Size, ffi.Pointer<ffi.Int64>)>(
    symbol: 'opusfile_dart_decode',
    assetId: 'package:opusfile_dart/opusfile_dart.dart')
external ffi.Pointer<ffi.UnsignedChar> opusfile_dart_decode(
  ffi.Pointer<ffi.Void> encoded,
  int length,
  ffi.Pointer<ffi.Int64> outLength,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.UnsignedChar>)>(
    symbol: 'opusfile_dart_free',
    assetId: 'package:opusfile_dart/opusfile_dart.dart')
external void opusfile_dart_free(
  ffi.Pointer<ffi.UnsignedChar> decoded,
);
